name: beirut
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  firebase_auth: ^0.16.1
  firebase: ^7.0.0
  provider: ^4.3.2
  google_fonts: ^1.1.0
  cloud_firestore: ^0.13.7
  image_picker: ^0.6.7+4
  firebase_storage: ^3.1.6
  modal_progress_hud: ^0.1.3
  animated_bottom_navigation_bar: ^0.1.2+2
  circular_reveal_animation: ^1.1.5
  toggle_switch: ^0.1.8
  url_launcher: ^5.5.0
  bot_toast: ^3.0.1
  firebase_database: ^3.1.6


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true


  assets:
    - images/


